"""initial schema

Revision ID: a8ffc8c2c200
Revises: 
Create Date: 2026-10-06 23:42:22.140507

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8ffc8c2c200'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_guild_id'), ['guild_id'], unique=False)

    op.create_table('guild_admins',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'discord_id')
    )
    op.create_table('guild_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('default_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_role_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('web_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('global_name', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('access_token', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_sessions_discord_id'), ['discord_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_sessions_discord_id'))

    op.drop_table('web_sessions')
    op.drop_table('guild_settings')
    op.drop_table('guild_admins')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_guild_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
